version: '3'

networks:
  default:
    external:
      name: main

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    env_file: .env
